"""Install and upgrade actions for the store.

Vendored (git-type) apps are installed by scaffolding an ``install.sh`` +
``run.sh`` pair (if absent) that reuse ``apps/_vendor_launcher.sh``, then
cloning into ``src/`` with a private venv. Upgrades fast-forward the clone,
wipe caches, and re-sync the venv — mirroring what the shell updater does, but
callable from the TUI/CLI.

Builtin apps ship with the deck; "installing" them is a no-op.
"""

from __future__ import annotations

import glob as _glob
import os
import shutil
import stat
import subprocess
import sys

from .registry import App
from . import appstate as st


# --- launcher scaffolding (install.sh must be the installer, not run.sh) ----

INSTALL_SH = """\
#!/usr/bin/env bash
# {name} — installer / updater (auto-generated by deck-store).
# Clones {url} into src/ with a private venv; offers fast-forward updates.
set -euo pipefail
DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
. "$DIR/../_vendor_launcher.sh"
vendor_sync "{id}" "{url}" "$DIR/src" "$@"
"""

RUN_SH = """\
#!/usr/bin/env bash
# {name} — launcher (auto-generated by deck-store).
set -euo pipefail
DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
. "$DIR/../_vendor_launcher.sh"
case "${{1:-}}" in --check-updates=*) exec "$DIR/install.sh" "$@" ;; esac
"$DIR/install.sh"
exec "$(vendor_python "$DIR/src")" "$DIR/src/{entry}" "$@"
"""


def _scaffold_launcher(app: App):
    d = st.app_dir(app)
    os.makedirs(d, exist_ok=True)
    inst = os.path.join(d, "install.sh")
    run = os.path.join(d, "run.sh")
    if not os.path.exists(inst):
        with open(inst, "w", newline="\n", encoding="utf-8") as f:
            f.write(INSTALL_SH.format(name=app.name, url=app.repo_url, id=app.id))
        _chmod_x(inst)
    if not os.path.exists(run):
        with open(run, "w", newline="\n", encoding="utf-8") as f:
            f.write(RUN_SH.format(name=app.name, entry=app.entry))
        _chmod_x(run)


def _chmod_x(path: str):
    try:
        os.chmod(path, 0o755)
    except Exception:
        pass


# --- venv + cache helpers (Python mirror of _vendor_launcher.sh) ------------

def _venv_python(src: str) -> str:
    for rel in (".venv/bin/python", ".venv/Scripts/python.exe", ".venv/Scripts/python"):
        p = os.path.join(src, rel)
        if os.path.exists(p):
            return p
    return shutil.which("python3") or shutil.which("python") or "python"


def _setup_venv(app: App, log=print):
    src = st.src_dir(app)
    venv = os.path.join(src, ".venv")
    base = shutil.which("python3") or shutil.which("python") or "python"
    if not os.path.isdir(venv):
        log(f"{app.id}: creating private venv ...")
        subprocess.run([base, "-m", "venv", venv], check=False)
    req = os.path.join(src, "requirements.txt")
    if os.path.exists(req):
        log(f"{app.id}: installing requirements ...")
        py = _venv_python(src)
        subprocess.run([py, "-m", "pip", "install", "--quiet", "-r", req], check=False)


def _clean_caches(app: App, log=print):
    src = st.src_dir(app)
    log(f"{app.id}: clearing caches ...")
    for root, dirs, files in os.walk(src):
        if ".git" in root.split(os.sep):
            continue
        for d in list(dirs):
            if d == "__pycache__":
                shutil.rmtree(os.path.join(root, d), ignore_errors=True)
        for fn in files:
            if fn.endswith(".pyc"):
                try:
                    os.remove(os.path.join(root, fn))
                except OSError:
                    pass
    # app-declared extra globs
    cfg = os.path.join(st.app_dir(app), ".update-clean")
    if os.path.exists(cfg):
        with open(cfg, encoding="utf-8") as f:
            for line in f:
                pat = line.split("#", 1)[0].strip()
                if not pat:
                    continue
                for match in _glob.glob(os.path.join(src, pat), recursive=True):
                    if os.path.isdir(match):
                        shutil.rmtree(match, ignore_errors=True)
                    else:
                        try:
                            os.remove(match)
                        except OSError:
                            pass


# --- public actions ---------------------------------------------------------

def install(app: App, log=print) -> bool:
    if not app.is_vendored:
        log(f"{app.id}: builtin — already part of the deck.")
        return True
    if st.is_cloned(app):
        log(f"{app.id}: already installed.")
        return True
    _scaffold_launcher(app)
    log(f"{app.id}: cloning {app.repo_url} ...")
    rc = subprocess.run(
        ["git", "clone", "--quiet", app.repo_url, st.src_dir(app)]
    ).returncode
    if rc != 0:
        log(f"{app.id}: clone failed.")
        return False
    _setup_venv(app, log)
    log(f"{app.id}: installed at {st.local_commit(app)}.")
    return True


def upgrade(app: App, state: st.StateStore, log=print) -> bool:
    if not app.is_vendored or not st.is_cloned(app):
        log(f"{app.id}: nothing to upgrade.")
        return False
    src = st.src_dir(app)
    rc, branch = st._git(src, "symbolic-ref", "--short", "HEAD")
    if rc != 0:
        branch = app.branch
    st._git(src, "fetch", "--quiet", "origin", timeout=60)
    rc, out = st._git(src, "merge", "--ff-only", f"origin/{branch}")
    if rc != 0:
        log(f"{app.id}: fast-forward failed (local edits in src/?) — skipped.")
        return False
    log(f"{app.id}: updated to {st.local_commit(app)}.")
    _clean_caches(app, log)       # wipe caches on every update pull
    _setup_venv(app, log)
    state.mark_updated(app)
    return True


def _force_rmtree(path: str) -> bool:
    """``rmtree`` that copes with read-only files. Returns True if it's gone.

    Git marks everything under ``.git/objects`` read-only, which makes a plain
    rmtree fail part-way (on Windows especially). Chmod-and-retry each failure,
    then report honestly — a half-deleted ``src/`` looks "not installed" but
    breaks the next clone, so this must never claim success it didn't achieve.
    """
    def handler(func, target, _exc):        # (func, path, exc) / (func, path, exc_info)
        try:
            os.chmod(target, stat.S_IWRITE)
            func(target)
        except OSError:
            pass

    if sys.version_info >= (3, 12):
        shutil.rmtree(path, onexc=handler)
    else:
        shutil.rmtree(path, onerror=handler)
    return not os.path.exists(path)


def uninstall(app: App, log=print) -> bool:
    """Remove the clone + venv (keeps the launcher scripts).

    Destructive: anything the app keeps inside ``src/`` (grimoire's tome and
    corpora, for one) goes with it. Callers must confirm first.
    """
    if not app.is_vendored:
        log(f"{app.id}: builtin — cannot uninstall.")
        return False
    src = st.src_dir(app)
    if not os.path.isdir(src):
        log(f"{app.id}: not installed.")
        return True
    if not _force_rmtree(src):
        log(f"{app.id}: could not fully remove {src} — delete it by hand.")
        return False
    log(f"{app.id}: removed clone.")
    return True
